Feature/sc 521/monorepo add zod for env variables
ShadowyCreators/modern-web3-monorepo pull request #10
Opened 2023-04-08 15:37 UTC by gabrir99

2023-04-09 08:08 UTC, harrysupertramp commented
Aggiungi per frontend e backend i relativi .env.template che al momento mancano in effetti

Manca l'integrazione di zod sulla cartella contract, che attualmente è l'unica che utilizza le env per l'hardhat config

2023-04-11 08:46 UTC, andreataglia requested changes

2023-04-11 08:46 UTC, andreataglia commented on packages/backend/src/services/zodValidation.ts
> +    PORT: z
metti su stessa riga

2023-04-11 08:46 UTC, andreataglia commented on packages/contracts/hardhat.config.ts
> +  url: <string>validatedENV.FORK_POL_URL
perchè sopra le chiami parsedEnv e qui validatedEnv? terrei sempre il nome parsedEnv

2023-04-11 08:46 UTC, andreataglia commented on packages/backend/src/services/zodValidation.ts
> +export const parsedEnv = envSchema.safeParse(process.env)
ma come safeParse? cosi se spacchi una env cmq ti parte? hai fatto la prova? hai capito qual è l'obiettivo?

2023-04-11 08:46 UTC, andreataglia commented on packages/contracts/src/services/zodValidation.ts
> +    FORK_ETH_URL: z
tutte su stessa riga

2023-04-14 08:46 UTC, andreataglia approved these changes

2023-04-14 08:46 UTC, merged